HolidayBookingApp-war/src/java/com/holidayBookingApp/admin/mbeans/AdminIndexManagedBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.holidayBookingApp.admin.mbeans;

import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpServletRequest;
import shared.holidayBookingApp.entities.Helper;
import shared.holidayBookingApp.entities.User;
import shared.holidayBookingApp.repository.HelperRepository;
import shared.holidayBookingApp.repository.UserRepository;

/**
 *
 * @author Lucky
 */
@ManagedBean(name = "adminIndexManagedBean")
@SessionScoped
public class AdminIndexManagedBean implements Serializable{

    /**
     * Creates a new instance of AdminIndexManagedBean
     */
    private Helper helper;
    private String name;
    @EJB
    private HelperRepository helperRepository;
    @EJB
    private UserRepository userRepository;
    
    public AdminIndexManagedBean() {
        this.name="Welcoome";
//        init_name();
//        this.helper = new Helper();
//        HttpServletRequest request = (HttpServletRequest) FacesContext.getCurrentInstance().getExternalContext().getRequest();
//        username = request.getRemoteUser();
    }

    public Helper getHelper() {
        return helper;
    }

    public void setHelper(Helper helper) {
        this.helper = helper;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public UserRepository getUserRepository() {
        return userRepository;
    }

    public void setUserRepository(UserRepository userRepository) {
        this.userRepository = userRepository;
    }

    public List<Helper> getAllHelpers(){
        try {
            return helperRepository.getHelper();
        } catch (Exception ex) {
            Logger.getLogger(AdminIndexManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
    
    public void init_name() {
        try {
            int userId = Integer.parseInt(FacesContext.getCurrentInstance().getExternalContext().getUserPrincipal().getName());
//            this.name = user.getFirstName() + " " + user.getLastName();
//            HttpServletRequest request = (HttpServletRequest) FacesContext.getCurrentInstance().getExternalContext().getRequest();

//        this.helper.setCurrentUser(request.getRemoteUser());

            this.name = Integer.toString(userId);
        } catch (Exception ex) {
            Logger.getLogger(AdminIndexManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
}

HolidayBookingApp-war/src/java/com/holidayBookingApp/admin/mbeans/AdminUsersManagedBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.holidayBookingApp.admin.mbeans;

import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import shared.holidayBookingApp.entities.User;
import shared.holidayBookingApp.repository.UserRepository;

/**
 *
 * @author Lucky
 */
@Named(value = "adminUsersManagedBean")
@SessionScoped
public class AdminUsersManagedBean implements Serializable {

    /**
     * Creates a new instance of UsersManagedBean
     */
    @EJB
    private UserRepository userRepository;
    
    public AdminUsersManagedBean() {
    }

    public UserRepository getUserRepository() {
        return userRepository;
    }

    public void setUserRepository(UserRepository userRepository) {
        this.userRepository = userRepository;
    }
    
    public List<User> getAllUsers() {
        try {
            return userRepository.getAllUsers();
        } catch (Exception ex) {
            Logger.getLogger(AdminUsersManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
}

HolidayBookingApp-war/src/java/com/holidayBookingApp/user/mbeans/UserBean.java
package com.java2s.common;

import java.io.Serializable;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
 
@ManagedBean(name="user")
@SessionScoped
public class UserBean implements Serializable{
	
	private static final long serialVersionUID = 1L;

}

HolidayBookingApp-war/web/admin/home.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui = "http://java.sun.com/jsf/facelets">
    <head>
        <title>Home</title>
        <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css" />
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    </head>
    <body>
        <ui:composition>testing</ui:composition>
    </body>
</html>

HolidayBookingApp-war/web/admin/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui = "http://java.sun.com/jsf/facelets">
    <head>
        <title>Home</title>
        <script src="../resources/js/jquery.min.js"></script>
        <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css" />
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
        
        <link href="../resources/css/customStyles/admin/home.css" rel="stylesheet" />
        <link href="../resources/css/customStyles/shared.css" rel="stylesheet" />
    </head>
    <body>
        <div class="container-fluid no-padding">
            
            <!-- Second navbar for profile settings -->
            <nav class="navbar navbar-inverse">
                <div class="container">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-4">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="#">Holiday Boutique</a>
                    </div>

                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="navbar-collapse-4">
                        <ul class="nav navbar-nav navbar-right">
                            <li><a href="index.xhtml">Home</a></li>
                            <li><a href="users.xhtml">Users</a></li>
                            <li><a href="#transactions">Transactions</a></li>
                            <li>
                                <a class="btn btn-default btn-outline btn-circle"  data-toggle="collapse" href="#nav-collapse4" aria-expanded="false" aria-controls="nav-collapse4">Profile <i class=""></i> </a>
                            </li>
                        </ul>
                        <ul class="collapse nav navbar-nav nav-collapse" role="search" id="nav-collapse4">
                            <li><a href="#">My profile</a></li>
                            <li><a href="#">Logout</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </div><!-- /.container -->
            </nav><!-- /.navbar -->
        </div><!-- /.container-fluid -->
        <div>#{adminIndexManagedBean.helper.currentUser}</div>
        
        <ui:repeat value="#{adminIndexManagedBean.allHelpers}" var="h" >
            <h:outputLabel value="#{h.currentUser}" />
        </ui:repeat>
        <div>
            home
        </div>
    </body>
</html>

HolidayBookingApp-war/web/admin/users.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <head>
        <title>Home</title>
        <script src="../resources/js/jquery.min.js"></script>
        <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css" />
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
        
        <link href="../resources/css/customStyles/admin/home.css" rel="stylesheet" />
        <link href="../resources/css/customStyles/shared.css" rel="stylesheet" />
    </head>
    <body>
        <div class="container-fluid no-padding">
            
            <!-- Second navbar for profile settings -->
            <nav class="navbar navbar-inverse">
                <div class="container">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-4">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="#home">Holiday Boutique</a>
                    </div>

                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="navbar-collapse-4">
                        <ul class="nav navbar-nav navbar-right">
                            <li><a href="index.xhtml">Home</a></li>
                            <li><a href="users.xhtml">Users</a></li>
                            <li><a href="#transactions">Transactions</a></li>
                            <li>
                                <a class="btn btn-default btn-outline btn-circle"  data-toggle="collapse" href="#nav-collapse4" aria-expanded="false" aria-controls="nav-collapse4">Profile <i class=""></i> </a>
                            </li>
                        </ul>
                        <ul class="collapse nav navbar-nav nav-collapse" role="search" id="nav-collapse4">
                            <li><a href="#">My profile</a></li>
                            <li><a href="#">Logout</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </div><!-- /.container -->
            </nav><!-- /.navbar -->
        </div><!-- /.container-fluid -->
        
        <ui:repeat value="#{adminUsersManagedBean.allUsers}" var="user" varStatus="status">
            <!--            <div class="panel-group" id="accordion">
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <h4 class="panel-title">
                                        <a data-toggle="collapse" data-parent="#accordion" href="#collapse1"><h:outputText value="#{user}" /></a>
                                    </h4>
                                </div>
                                <div id="collapse1" class="panel-collapse collapse in">
                                    <div class="panel-body">Lorem ipsum dolor sit amet, consectetur adipisicing elit,
                                        sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                                        quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</div>
                                </div>
                            </div>
                        </div>-->
            <tr> 
                <td>
                    <h:outputText value="#{user.firstName}" id="propertyID" /> 
                </td>
                <td> 
                    <h:outputLabel id="Price" value="Price:"  />
                </td>
                <td> 
                    <h:outputText id="outPrice" value="#{user.lastName}"  />
                </td>
                <td> 
                    <h:outputLabel id="Address" value="Address:"/></td>
                <td> 
                    <h:outputText id="outAddress" value="#{user.email}"></h:outputText>
                </td>
            </tr> 
        </ui:repeat>
    </body>
</html>